appname = descuento_academico_crud
httpport = ${DESCUENTO_ACADEMICO_CRUD_HTTP_PORT}
runmode = ${DESCUENTO_ACADEMICO_CRUD_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
PGuser=${DESCUENTO_ACADEMICO_CRUD_PGUSER}
PGpass=${DESCUENTO_ACADEMICO_CRUD_PGPASS}
PGhost=${DESCUENTO_ACADEMICO_CRUD_PGHOST}
PGport=${DESCUENTO_ACADEMICO_CRUD_PGPORT}
PGdb=${DESCUENTO_ACADEMICO_CRUD_PGDB}
PGschema=${DESCUENTO_ACADEMICO_CRUD_SCHEMA}
